### ISSUE TITLE
ikd-forest with fastlio

### ISSUE THREAD

**Issue by satyajitghana** [hku-mars/PULSAR#1]
Hi,
I wanted to ask, the FASTLIO2 included in this repository is still linked to ikd-tree. So is FASTLIO2 with ikd-tree better than FASTLIO2 with ikd-forest for PULSAR?

**Comment by lawrence-cn** [comment]
The FAST-LIO2 used in PULSAR is still based on the ikd-tree since its performance is enough. So far we still have not compared their performance systematacially (may depend on parameter adjustment), so we cannot say which is better.
